services:
  thingsboard:
    image: "store/thingsboard/tb-pe:3.3.2PE"
    ports:
      - "8080:8080"
      #- "1883:1883" # MQTT port
      #- "7070:7070" # Edge RPC port
    environment:
      TB_QUEUE_TYPE: in-memory
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/thingsboard
      TB_LICENSE_SECRET: PUT_YOUR_LICENSE_SECRET_HERE
      TB_LICENSE_INSTANCE_DATA_FILE: /data/license.data
    #volumes:
      #- ~/.mytbpe-data:/data
      #- ~/.mytbpe-logs:/var/log/thingsboard
    secrets:
      - postgres
    restart: always

  postgres:
    image: "postgres:12"
    environment:
      POSTGRES_DB: thingsboard
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres
    secrets:
      - postgres
    restart: always

  # TODO kafka queue


secrets:
  postgres:
    file: ./secrets/postgres.txt
