services:
  thingsboard:
    # Use Community Edition for development purposes
    # https://thingsboard.io/docs/user-guide/install/docker/
    build:
      context: ./thingsboard
      dockerfile: Dockerfile
      args:
        TB_VERSION: 3.3.2pe
    ports:
      - "8080:8080"
      #- "1883:1883" # MQTT port
      #- "7070:7070" # Edge RPC port
    environment:
      # https://thingsboard.io/docs/pe/user-guide/install/config/
      TB_LICENSE_INSTANCE_DATA_FILE: /data/license.data
      HTTP_BIND_PORT: 8080
      TB_QUEUE_TYPE: rabbitmq
      # RabbitMQ connection
      TB_QUEUE_RABBIT_MQ_USERNAME: thingsboard
      TB_QUEUE_RABBIT_MQ_HOST: queue
      TB_QUEUE_RABBIT_MQ_PORT: 5672
    env_file:
      - ./secrets/thingsboard_secrets.env
    volumes:
      - ./thingsboard/thingsboard.conf:/etc/thingsboard/conf/thingsboard.conf
      #- ~/.mytbpe-data:/data
      #- ~/.mytbpe-logs:/var/log/thingsboard
    restart: always

  # System database
  postgres:
    image: "postgres:12"
    environment:
      POSTGRES_DB: thingsboard
      POSTGRES_USER: thingsboard
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres
    secrets:
      - postgres
    restart: always

  # Message broker
  queue:
    # https://hub.docker.com/_/rabbitmq
    # https://www.rabbitmq.com/configure.html
    image: "rabbitmq:3.9-management"
    ports:
      - "15672:15672" # Management console
    environment:
      RABBITMQ_NODE_PORT: 5672
      RABBITMQ_DEFAULT_USER: thingsboard
    env_file:
      - ./secrets/rabbitmq_secrets.env

secrets:
  postgres:
    file: ./secrets/postgres.txt
  thingsboard_license:
    file: ./secrets/thingsboard_license.txt
